# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LaminaOrthotropic', [dirname(__file__)])
        except ImportError:
            import _LaminaOrthotropic
            return _LaminaOrthotropic
        if fp is not None:
            try:
                _mod = imp.load_module('_LaminaOrthotropic', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LaminaOrthotropic = swig_import_helper()
    del swig_import_helper
else:
    import _LaminaOrthotropic
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class LaminaOrthotropic(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LaminaOrthotropic, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LaminaOrthotropic, name)
    __repr__ = _swig_repr
    __swig_setmethods__["material"] = _LaminaOrthotropic.LaminaOrthotropic_material_set
    __swig_getmethods__["material"] = _LaminaOrthotropic.LaminaOrthotropic_material_get
    if _newclass:
        material = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_material_get, _LaminaOrthotropic.LaminaOrthotropic_material_set)
    __swig_setmethods__["orientation"] = _LaminaOrthotropic.LaminaOrthotropic_orientation_set
    __swig_getmethods__["orientation"] = _LaminaOrthotropic.LaminaOrthotropic_orientation_get
    if _newclass:
        orientation = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_orientation_get, _LaminaOrthotropic.LaminaOrthotropic_orientation_set)
    __swig_setmethods__["thickness"] = _LaminaOrthotropic.LaminaOrthotropic_thickness_set
    __swig_getmethods__["thickness"] = _LaminaOrthotropic.LaminaOrthotropic_thickness_get
    if _newclass:
        thickness = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_thickness_get, _LaminaOrthotropic.LaminaOrthotropic_thickness_set)
    __swig_setmethods__["Q11"] = _LaminaOrthotropic.LaminaOrthotropic_Q11_set
    __swig_getmethods__["Q11"] = _LaminaOrthotropic.LaminaOrthotropic_Q11_get
    if _newclass:
        Q11 = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_Q11_get, _LaminaOrthotropic.LaminaOrthotropic_Q11_set)
    __swig_setmethods__["Q22"] = _LaminaOrthotropic.LaminaOrthotropic_Q22_set
    __swig_getmethods__["Q22"] = _LaminaOrthotropic.LaminaOrthotropic_Q22_get
    if _newclass:
        Q22 = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_Q22_get, _LaminaOrthotropic.LaminaOrthotropic_Q22_set)
    __swig_setmethods__["Q12"] = _LaminaOrthotropic.LaminaOrthotropic_Q12_set
    __swig_getmethods__["Q12"] = _LaminaOrthotropic.LaminaOrthotropic_Q12_get
    if _newclass:
        Q12 = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_Q12_get, _LaminaOrthotropic.LaminaOrthotropic_Q12_set)
    __swig_setmethods__["Q66"] = _LaminaOrthotropic.LaminaOrthotropic_Q66_set
    __swig_getmethods__["Q66"] = _LaminaOrthotropic.LaminaOrthotropic_Q66_get
    if _newclass:
        Q66 = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_Q66_get, _LaminaOrthotropic.LaminaOrthotropic_Q66_set)
    __swig_setmethods__["Q16"] = _LaminaOrthotropic.LaminaOrthotropic_Q16_set
    __swig_getmethods__["Q16"] = _LaminaOrthotropic.LaminaOrthotropic_Q16_get
    if _newclass:
        Q16 = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_Q16_get, _LaminaOrthotropic.LaminaOrthotropic_Q16_set)
    __swig_setmethods__["Q26"] = _LaminaOrthotropic.LaminaOrthotropic_Q26_set
    __swig_getmethods__["Q26"] = _LaminaOrthotropic.LaminaOrthotropic_Q26_get
    if _newclass:
        Q26 = _swig_property(_LaminaOrthotropic.LaminaOrthotropic_Q26_get, _LaminaOrthotropic.LaminaOrthotropic_Q26_set)

    def calculate_elastic_constants(self):
        return _LaminaOrthotropic.LaminaOrthotropic_calculate_elastic_constants(self)

    def __init__(self):
        this = _LaminaOrthotropic.new_LaminaOrthotropic()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _LaminaOrthotropic.delete_LaminaOrthotropic
    __del__ = lambda self: None
LaminaOrthotropic_swigregister = _LaminaOrthotropic.LaminaOrthotropic_swigregister
LaminaOrthotropic_swigregister(LaminaOrthotropic)

# This file is compatible with both classic and new-style classes.


