# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_MaterialOrthotropic', [dirname(__file__)])
        except ImportError:
            import _MaterialOrthotropic
            return _MaterialOrthotropic
        if fp is not None:
            try:
                _mod = imp.load_module('_MaterialOrthotropic', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _MaterialOrthotropic = swig_import_helper()
    del swig_import_helper
else:
    import _MaterialOrthotropic
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class MaterialOrthotropic(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MaterialOrthotropic, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MaterialOrthotropic, name)
    __repr__ = _swig_repr
    __swig_setmethods__["material_name"] = _MaterialOrthotropic.MaterialOrthotropic_material_name_set
    __swig_getmethods__["material_name"] = _MaterialOrthotropic.MaterialOrthotropic_material_name_get
    if _newclass:
        material_name = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_material_name_get, _MaterialOrthotropic.MaterialOrthotropic_material_name_set)
    __swig_setmethods__["material_id"] = _MaterialOrthotropic.MaterialOrthotropic_material_id_set
    __swig_getmethods__["material_id"] = _MaterialOrthotropic.MaterialOrthotropic_material_id_get
    if _newclass:
        material_id = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_material_id_get, _MaterialOrthotropic.MaterialOrthotropic_material_id_set)
    __swig_setmethods__["material_type"] = _MaterialOrthotropic.MaterialOrthotropic_material_type_set
    __swig_getmethods__["material_type"] = _MaterialOrthotropic.MaterialOrthotropic_material_type_get
    if _newclass:
        material_type = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_material_type_get, _MaterialOrthotropic.MaterialOrthotropic_material_type_set)
    __swig_setmethods__["material_product"] = _MaterialOrthotropic.MaterialOrthotropic_material_product_set
    __swig_getmethods__["material_product"] = _MaterialOrthotropic.MaterialOrthotropic_material_product_get
    if _newclass:
        material_product = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_material_product_get, _MaterialOrthotropic.MaterialOrthotropic_material_product_set)
    __swig_setmethods__["env_condition"] = _MaterialOrthotropic.MaterialOrthotropic_env_condition_set
    __swig_getmethods__["env_condition"] = _MaterialOrthotropic.MaterialOrthotropic_env_condition_get
    if _newclass:
        env_condition = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_env_condition_get, _MaterialOrthotropic.MaterialOrthotropic_env_condition_set)
    __swig_setmethods__["application"] = _MaterialOrthotropic.MaterialOrthotropic_application_set
    __swig_getmethods__["application"] = _MaterialOrthotropic.MaterialOrthotropic_application_get
    if _newclass:
        application = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_application_get, _MaterialOrthotropic.MaterialOrthotropic_application_set)
    __swig_setmethods__["E11"] = _MaterialOrthotropic.MaterialOrthotropic_E11_set
    __swig_getmethods__["E11"] = _MaterialOrthotropic.MaterialOrthotropic_E11_get
    if _newclass:
        E11 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E11_get, _MaterialOrthotropic.MaterialOrthotropic_E11_set)
    __swig_setmethods__["E22"] = _MaterialOrthotropic.MaterialOrthotropic_E22_set
    __swig_getmethods__["E22"] = _MaterialOrthotropic.MaterialOrthotropic_E22_get
    if _newclass:
        E22 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E22_get, _MaterialOrthotropic.MaterialOrthotropic_E22_set)
    __swig_setmethods__["G12"] = _MaterialOrthotropic.MaterialOrthotropic_G12_set
    __swig_getmethods__["G12"] = _MaterialOrthotropic.MaterialOrthotropic_G12_get
    if _newclass:
        G12 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_G12_get, _MaterialOrthotropic.MaterialOrthotropic_G12_set)
    __swig_setmethods__["nu12"] = _MaterialOrthotropic.MaterialOrthotropic_nu12_set
    __swig_getmethods__["nu12"] = _MaterialOrthotropic.MaterialOrthotropic_nu12_get
    if _newclass:
        nu12 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_nu12_get, _MaterialOrthotropic.MaterialOrthotropic_nu12_set)
    __swig_setmethods__["nu21"] = _MaterialOrthotropic.MaterialOrthotropic_nu21_set
    __swig_getmethods__["nu21"] = _MaterialOrthotropic.MaterialOrthotropic_nu21_get
    if _newclass:
        nu21 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_nu21_get, _MaterialOrthotropic.MaterialOrthotropic_nu21_set)
    __swig_setmethods__["nu32"] = _MaterialOrthotropic.MaterialOrthotropic_nu32_set
    __swig_getmethods__["nu32"] = _MaterialOrthotropic.MaterialOrthotropic_nu32_get
    if _newclass:
        nu32 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_nu32_get, _MaterialOrthotropic.MaterialOrthotropic_nu32_set)
    __swig_setmethods__["E1t"] = _MaterialOrthotropic.MaterialOrthotropic_E1t_set
    __swig_getmethods__["E1t"] = _MaterialOrthotropic.MaterialOrthotropic_E1t_get
    if _newclass:
        E1t = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E1t_get, _MaterialOrthotropic.MaterialOrthotropic_E1t_set)
    __swig_setmethods__["E1c"] = _MaterialOrthotropic.MaterialOrthotropic_E1c_set
    __swig_getmethods__["E1c"] = _MaterialOrthotropic.MaterialOrthotropic_E1c_get
    if _newclass:
        E1c = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E1c_get, _MaterialOrthotropic.MaterialOrthotropic_E1c_set)
    __swig_setmethods__["E2t"] = _MaterialOrthotropic.MaterialOrthotropic_E2t_set
    __swig_getmethods__["E2t"] = _MaterialOrthotropic.MaterialOrthotropic_E2t_get
    if _newclass:
        E2t = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E2t_get, _MaterialOrthotropic.MaterialOrthotropic_E2t_set)
    __swig_setmethods__["E2c"] = _MaterialOrthotropic.MaterialOrthotropic_E2c_set
    __swig_getmethods__["E2c"] = _MaterialOrthotropic.MaterialOrthotropic_E2c_get
    if _newclass:
        E2c = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E2c_get, _MaterialOrthotropic.MaterialOrthotropic_E2c_set)
    __swig_setmethods__["E12"] = _MaterialOrthotropic.MaterialOrthotropic_E12_set
    __swig_getmethods__["E12"] = _MaterialOrthotropic.MaterialOrthotropic_E12_get
    if _newclass:
        E12 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E12_get, _MaterialOrthotropic.MaterialOrthotropic_E12_set)
    __swig_setmethods__["E3t"] = _MaterialOrthotropic.MaterialOrthotropic_E3t_set
    __swig_getmethods__["E3t"] = _MaterialOrthotropic.MaterialOrthotropic_E3t_get
    if _newclass:
        E3t = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E3t_get, _MaterialOrthotropic.MaterialOrthotropic_E3t_set)
    __swig_setmethods__["E3c"] = _MaterialOrthotropic.MaterialOrthotropic_E3c_set
    __swig_getmethods__["E3c"] = _MaterialOrthotropic.MaterialOrthotropic_E3c_get
    if _newclass:
        E3c = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E3c_get, _MaterialOrthotropic.MaterialOrthotropic_E3c_set)
    __swig_setmethods__["E23"] = _MaterialOrthotropic.MaterialOrthotropic_E23_set
    __swig_getmethods__["E23"] = _MaterialOrthotropic.MaterialOrthotropic_E23_get
    if _newclass:
        E23 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_E23_get, _MaterialOrthotropic.MaterialOrthotropic_E23_set)
    __swig_setmethods__["F1t"] = _MaterialOrthotropic.MaterialOrthotropic_F1t_set
    __swig_getmethods__["F1t"] = _MaterialOrthotropic.MaterialOrthotropic_F1t_get
    if _newclass:
        F1t = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F1t_get, _MaterialOrthotropic.MaterialOrthotropic_F1t_set)
    __swig_setmethods__["F1c"] = _MaterialOrthotropic.MaterialOrthotropic_F1c_set
    __swig_getmethods__["F1c"] = _MaterialOrthotropic.MaterialOrthotropic_F1c_get
    if _newclass:
        F1c = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F1c_get, _MaterialOrthotropic.MaterialOrthotropic_F1c_set)
    __swig_setmethods__["F2t"] = _MaterialOrthotropic.MaterialOrthotropic_F2t_set
    __swig_getmethods__["F2t"] = _MaterialOrthotropic.MaterialOrthotropic_F2t_get
    if _newclass:
        F2t = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F2t_get, _MaterialOrthotropic.MaterialOrthotropic_F2t_set)
    __swig_setmethods__["F2c"] = _MaterialOrthotropic.MaterialOrthotropic_F2c_set
    __swig_getmethods__["F2c"] = _MaterialOrthotropic.MaterialOrthotropic_F2c_get
    if _newclass:
        F2c = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F2c_get, _MaterialOrthotropic.MaterialOrthotropic_F2c_set)
    __swig_setmethods__["F12"] = _MaterialOrthotropic.MaterialOrthotropic_F12_set
    __swig_getmethods__["F12"] = _MaterialOrthotropic.MaterialOrthotropic_F12_get
    if _newclass:
        F12 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F12_get, _MaterialOrthotropic.MaterialOrthotropic_F12_set)
    __swig_setmethods__["F3t"] = _MaterialOrthotropic.MaterialOrthotropic_F3t_set
    __swig_getmethods__["F3t"] = _MaterialOrthotropic.MaterialOrthotropic_F3t_get
    if _newclass:
        F3t = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F3t_get, _MaterialOrthotropic.MaterialOrthotropic_F3t_set)
    __swig_setmethods__["F3c"] = _MaterialOrthotropic.MaterialOrthotropic_F3c_set
    __swig_getmethods__["F3c"] = _MaterialOrthotropic.MaterialOrthotropic_F3c_get
    if _newclass:
        F3c = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F3c_get, _MaterialOrthotropic.MaterialOrthotropic_F3c_set)
    __swig_setmethods__["F23"] = _MaterialOrthotropic.MaterialOrthotropic_F23_set
    __swig_getmethods__["F23"] = _MaterialOrthotropic.MaterialOrthotropic_F23_get
    if _newclass:
        F23 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_F23_get, _MaterialOrthotropic.MaterialOrthotropic_F23_set)
    __swig_setmethods__["C11"] = _MaterialOrthotropic.MaterialOrthotropic_C11_set
    __swig_getmethods__["C11"] = _MaterialOrthotropic.MaterialOrthotropic_C11_get
    if _newclass:
        C11 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_C11_get, _MaterialOrthotropic.MaterialOrthotropic_C11_set)
    __swig_setmethods__["C22"] = _MaterialOrthotropic.MaterialOrthotropic_C22_set
    __swig_getmethods__["C22"] = _MaterialOrthotropic.MaterialOrthotropic_C22_get
    if _newclass:
        C22 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_C22_get, _MaterialOrthotropic.MaterialOrthotropic_C22_set)
    __swig_setmethods__["C12"] = _MaterialOrthotropic.MaterialOrthotropic_C12_set
    __swig_getmethods__["C12"] = _MaterialOrthotropic.MaterialOrthotropic_C12_get
    if _newclass:
        C12 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_C12_get, _MaterialOrthotropic.MaterialOrthotropic_C12_set)
    __swig_setmethods__["C66"] = _MaterialOrthotropic.MaterialOrthotropic_C66_set
    __swig_getmethods__["C66"] = _MaterialOrthotropic.MaterialOrthotropic_C66_get
    if _newclass:
        C66 = _swig_property(_MaterialOrthotropic.MaterialOrthotropic_C66_get, _MaterialOrthotropic.MaterialOrthotropic_C66_set)

    def calculate_elastic_constants(self):
        return _MaterialOrthotropic.MaterialOrthotropic_calculate_elastic_constants(self)

    def __init__(self):
        this = _MaterialOrthotropic.new_MaterialOrthotropic()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _MaterialOrthotropic.delete_MaterialOrthotropic
    __del__ = lambda self: None
MaterialOrthotropic_swigregister = _MaterialOrthotropic.MaterialOrthotropic_swigregister
MaterialOrthotropic_swigregister(MaterialOrthotropic)

# This file is compatible with both classic and new-style classes.


